default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: rps_development

test:
  <<: *default
  database: rps_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
